### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Deviltriss** [MrPleasant-exe/Destiny-2-Solo-lobby#2]
Does this still work?
I have tried numerous times to get it to work by following reddit guide, however still cant make it work.

Also does this work, with 2 in a fireteam? as I am looking to play with a friend.

regards

**Comment by Pleasant-exe** [comment]
It works yes, just make sure to check the latest release and follow new instructions, its best to try and start say a strike alone and have a friend join in case.

**Comment by Pleasant-exe** [comment]
https://github.com/MrPleasant-exe/Destiny-2-Solo-lobby/releases/tag/3
