### ISSUE TITLE
Still Working?

### ISSUE THREAD

**Issue by JamIsJam88** [MrPleasant-exe/Destiny-2-Solo-lobby#4]
Hey the first time I followed your instructions it worked! However, the next destination I loaded, it stopped working from then on.

Do you have to use "set-executionpolicy remotesigned" every time before you load the DestinySoloLobby.ps1 script?
I also tried using "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass".

I've tried using Resource Monitor to see what other ports Destiny 2 is listening on and I've blocked a specific 7xxx, 2xxxx, and any ranges of 4xxxx and 5xxxx. There are also 6xxxx but if I block those it gives me an error when trying to load the script.

Is there anything I am missing?

**Comment by Pleasant-exe** [comment]
I have been told this a few times lately, im not yet sure what the issue is currently, in the meantime i suggest running in Powershell ISE which can be found at "C:\Windows\system32\WindowsPowerShell\v1.0\powershell_ise.exe"

**Comment by JamIsJam88** [comment]
Thanks for the response! I just tried to run ISE in Admin mode and I got this error when trying to run the script. Any idea what this means?

Exception calling "ReadKey" with "1" argument(s): "The method or operation is not implemented."
At C:\Users\trini\Desktop\DestinySoloLobby.ps1:27 char:1
+ $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown');
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotImplementedException

**Comment by Pleasant-exe** [comment]
Sorry, again i should have noted that you will still need to run the original commands again in ISE.

**Comment by JamIsJam88** [comment]
Oh I did use the commands below and said yes to all just before.

set-executionpolicy remotesigned
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
