### ISSUE TITLE
Exception calling "ReadKey"

### ISSUE THREAD

**Issue by ByYudkowskysTentacle** [MrPleasant-exe/Destiny-2-Solo-lobby#5]
Totally new at this so apologies if this is an obvious question, but I'm getting the following error upon running the script in PowerShell ISE; I have run the two commands and am able to run scripts in PowerShell without an Admin prompt.

Exception calling "ReadKey" with "1" argument(s): "The method or operation is not implemented."
At C:\Users\Gungnir\Desktop\DestinySoloLobby.ps1:27 char:1
+ $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown');
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotImplementedException

**Comment by Pleasant-exe** [comment]
Hey, 

This is an annoying issue i need to fix, i would suggest going with the version i just pushed for now https://github.com/MrPleasant-exe/Destiny-2-Solo-lobby/blob/master/DestinySoloLobby.ps1
