### ISSUE TITLE
Beyond light

### ISSUE THREAD

**Issue by coolgameinside** [MrPleasant-exe/Destiny-2-Solo-lobby#6]
Does not work anymore?

**Comment by Pleasant-exe** [comment]
It should work, i dont have any issues nor do my clan, are you reporting an issue or just asking?

**Comment by coolgameinside** [comment]
Doesn't work for me, tried both methods.

**Comment by KoshiirRa** [comment]
No success here on both methods either.

**Comment by amarcionek** [comment]
Heads up, its working for me in BL. It wasn't at first, which is why I came here, but then I discovered MY ENTIRE FIREWALL WAS DISABLED and so the rules were not taking affect.

**Comment by KoshiirRa** [comment]
*facepalm* Mine was disabled too.

**Comment by coolgameinside** [comment]
Has something changed? I always have the Windows firewall turned off by default, and scriprt work, after update he is not.

**Comment by Pleasant-exe** [comment]
You need to have the firewall enabled to actually block matchmaking, im not sure what you did before.
