### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Bukowskaii** [MrPleasant-exe/Destiny-2-Solo-lobby#8]
As of destiny hotfix 3.2.0.3

**Comment by JasonJulias** [comment]
Works for me after hotfix.

**Comment by Pleasant-exe** [comment]
Sorry for the long response but it does work.

**Comment by scryptio** [comment]
Doesn't really work. During the initial search it stays at 1/3 until it begins the loading progress. Once in I am always paired with other guys.
